name: Unit Tests - Multiple PHP Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    name: run (PHP ${{ matrix.php-versions }}, phpunit ${{ matrix.phpunit-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.0', '7.4', '7.3', '7.2', '7.1', '7.0', '5.6']
    steps:
    - name: Checkout Action
      uses: actions/checkout@v3

      #- name: Composer Action
      #uses: php-actions/composer@v6
      #with:
      #  dev: no

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        tools: phpunit, composer

    - name: Run composer install
      run: composer install --prefer-dist --no-interaction

    - name: Run php --version
      run: php --version

    - name: Run composer run-script phpversion
      run:  composer run-script phpversion

    - name: Run phpunit
      run: composer exec phpunit
