name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: composer update --no-interaction --optimize-autoloader

      - uses: docker://oskarstark/phpstan-ga:1.6.0
        with:
          entrypoint: /composer/vendor/bin/phpstan
          args: analyze --no-progress --level 5 src
