name: Windows/Mac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['windows-latest', 'macos-latest']
    steps:
    - name: Checkout Action
      uses: actions/checkout@v3

      #- name: Setup PHP
      #uses: shivammathur/setup-php@v2
      #with:
      #  php-version: '8.1'
      #  coverage: none
      #  tools: phpunit

    - name: Run composer install
      run: composer install --prefer-dist --no-interaction

    - name: Run phpunit
      run: phpunit
