name: Windows/Mac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['windows-latest', 'macos-latest']
    steps:
    - name: Checkout Action
      uses: actions/checkout@v3

    - name: Run composer install
      run: composer install --prefer-dist --no-interaction

    - name: Run tests
      run: composer run-script tests
