name: CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest'] # ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-versions: [7.3] #['7.3', '7.4', '8.0', '8.1']
        phpunit-versions: ['latest']
        include:
        - operating-system: 'ubuntu-latest'
          php-versions: '7.2'
          phpunit-versions: 8
        - operating-system: 'ubuntu-latest'
          php-versions: '7.1'
          phpunit-versions: 7
    steps:
    - name: Checkout Action
      uses: actions/checkout@v3

    - name: Composer Action
      uses: php-actions/composer@v6
      with:
        dev: no

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        tools: phpunit:${{ matrix.phpunit-versions }}

    - name: Run phpunit --version
      run: composer exec phpunit -- --version

    - name: Run phpunit
      run: composer exec phpunit
