name: CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-versions: ['8.1']
    steps:
    - name: Checkout Action
      uses: actions/checkout@v3

    - name: Composer Action
      uses: php-actions/composer@v6
      with:
        dev: no

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        tools: phpunit

    - name: Run phpunit
      run: composer exec phpunit
